# Generated by Django 4.2.28 on 2026-03-01 16:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('previous_state', models.JSONField(null=True)),
                ('new_state', models.JSONField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('what_is_needed', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('needed_by_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('decision_notes', models.TextField(blank=True)),
                ('date_decided', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('kr_type', models.CharField(choices=[('numeric', 'Numeric'), ('percentage', 'Percentage'), ('boolean', 'Boolean'), ('currency', 'Currency')], default='numeric', max_length=20)),
                ('start_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=5)),
                ('rag_status', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=10)),
                ('due_date', models.DateField()),
                ('related_files_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyResultHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_value', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('new_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('previous_rag_status', models.CharField(blank=True, max_length=10)),
                ('new_rag_status', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('due_date', models.DateField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskBlocker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('rag_status', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], max_length=10)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('date_identified', models.DateField(auto_now_add=True)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='okr_app.keyresult')),
            ],
        ),
    ]
