# Generated by Django 4.2.28 on 2026-03-01 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('okr_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskblocker',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskblocker',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.organization'),
        ),
        migrations.AddField(
            model_name='riskblocker',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objective',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_objectives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objective',
            name='co_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_owned_objectives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objective',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='users_app.organization'),
        ),
        migrations.AddField(
            model_name='objective',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_objectives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objective',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='users_app.team'),
        ),
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keyresulthistory',
            name='key_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='okr_app.keyresult'),
        ),
        migrations.AddField(
            model_name='keyresulthistory',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='co_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_owned_key_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okr_app.objective'),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='users_app.organization'),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_key_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionresource',
            name='decision_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionresource',
            name='key_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='okr_app.keyresult'),
        ),
        migrations.AddField(
            model_name='decisionresource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.organization'),
        ),
        migrations.AddField(
            model_name='decisionresource',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='key_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishments', to='okr_app.keyresult'),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.organization'),
        ),
    ]
