# Generated by Django 5.2.11 on 2026-03-04 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr_app', '0002_initial'),
        ('users_app', '0002_add_key_activity_metric_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='key_activity',
            field=models.TextField(blank=True, help_text='Key activities to be performed for this KR.'),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='metric',
            field=models.CharField(blank=True, help_text='The specific metric used to measure progress.', max_length=255),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyresulthistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_result_histories', to='users_app.organization'),
        ),
        migrations.AddIndex(
            model_name='keyresult',
            index=models.Index(fields=['organization', 'due_date'], name='kr_org_due_idx'),
        ),
        migrations.AddIndex(
            model_name='keyresulthistory',
            index=models.Index(fields=['organization', 'recorded_at'], name='krh_org_recorded_idx'),
        ),
        migrations.AddIndex(
            model_name='keyresulthistory',
            index=models.Index(fields=['key_result', 'recorded_at'], name='krh_kr_recorded_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['organization', 'status'], name='obj_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='riskblocker',
            index=models.Index(fields=['organization', 'rag_status'], name='risk_org_rag_idx'),
        ),
    ]
