# Generated by Django 5.2.11 on 2026-03-04 09:15

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail SMTP'), ('sendgrid', 'SendGrid'), ('aws_ses', 'AWS SES')], default='gmail', max_length=20)),
                ('display_name', models.CharField(default='Argos', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('gmail_user', models.EmailField(blank=True, default='', max_length=254)),
                ('gmail_app_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('sendgrid_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('sendgrid_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('aws_access_key_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('aws_secret_access_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('aws_region', models.CharField(blank=True, default='us-east-1', max_length=50)),
                ('aws_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'organization', 'is_active'], name='mem_user_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='org_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='org_status_idx'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='users_app.organization'),
        ),
    ]
